export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const REGISTER_CLEAR = 'REGISTER_CLEAR';
export const REGISTER_ERROR_CLEAR = 'REGISTER_ERROR_CLEAR';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_ERROR_CLEAR = 'LOGIN_ERROR_CLEAR';

export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';
export const GET_USER_FROM_LOCAL_STORAGE = 'GET_USER_FROM_LOCAL_STORAGE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';

export const SEARCH_CREATE_ALBUM_REQUEST = 'SEARCH_CREATE_ALBUM_REQUEST';
export const SEARCH_CREATE_ALBUM_SUCCESS = 'SEARCH_CREATE_ALBUM_SUCCESS';
export const SEARCH_CREATE_ALBUM_FAILURE = 'SEARCH_CREATE_ALBUM_FAILURE';
export const SEARCH_CREATE_ALBUM_ERROR_CLEAR =
  'SEARCH_CREATE_ALBUM_ERROR_CLEAR';

export const SEARCH_USERS_REQUEST = 'SEARCH_USERS_REQUEST';
export const SEARCH_USERS_SUCCESS = 'SEARCH_USERS_SUCCESS';
export const SEARCH_USERS_FAILURE = 'SEARCH_USERS_FAILURE';
export const SEARCH_USERS_ERROR_CLEAR = 'SEARCH_USERS_ERROR_CLEAR';
export const SEARCH_CREATE_ALBUM_DATA_CLEAR = 'SEARCH_CREATE_ALBUM_DATA_CLEAR';

export const EDIT_VENDOR_REQUEST = 'EDIT_VENDOR_REQUEST';
export const EDIT_VENDOR_SUCCESS = 'EDIT_VENDOR_SUCCESS';
export const EDIT_VENDOR_FAILURE = 'EDIT_VENDOR_FAILURE';
export const EDIT_VENDOR_ERROR_CLEAR = 'EDIT_VENDOR_ERROR_CLEAR';

export const CREATE_VENDOR_PROFILE_REQUEST = 'CREATE_VENDOR_PROFILE_REQUEST';
export const CREATE_VENDOR_PROFILE_SUCCESS = 'CREATE_VENDOR_PROFILE_SUCCESS';
export const CREATE_VENDOR_PROFILE_FAILURE = 'CREATE_VENDOR_PROFILE_FAILURE';
export const CREATE_VENDOR_PROFILE_ERROR_CLEAR =
  'CREATE_VENDOR_PROFILE_ERROR_CLEAR';

export const GET_VENDOR_REQUEST = 'GET_VENDOR_REQUEST';
export const GET_VENDOR_SUCCESS = 'GET_VENDOR_SUCCESS';
export const GET_VENDOR_FAILURE = 'GET_VENDOR_FAILURE';

export const LOGIN_FACEBOOK_REQUEST = 'LOGIN_FACEBOOK_REQUEST';
export const LOGIN_FACEBOOK_SUCCESS = 'LOGIN_FACEBOOK_SUCCESS';
export const LOGIN_FACEBOOK_FAILURE = 'LOGIN_FACEBOOK_FAILURE';
export const LOGIN_FACEBOOK_ERROR_CLEAR = 'LOGIN_FACEBOOK_ERROR_CLEAR';

export const LOGIN_GOOGLE_REQUEST = 'LOGIN_GOOGLE_REQUEST';
export const LOGIN_GOOGLE_SUCCESS = 'LOGIN_GOOGLE_SUCCESS';
export const LOGIN_GOOGLE_FAILURE = 'LOGIN_GOOGLE_FAILURE';
export const LOGIN_GOOGLE_ERROR_CLEAR = 'LOGIN_GOOGLE_ERROR_CLEAR';

export const GET_ALBUM_REQUEST = 'GET_ALBUM_REQUEST';
export const GET_ALBUM_SUCCESS = 'GET_ALBUM_SUCCESS';
export const GET_ALBUM_FAILURE = 'GET_ALBUM_FAILURE';

export const CREATE_ALBUM_REQUEST = 'CREATE_ALBUM_REQUEST';
export const CREATE_ALBUM_SUCCESS = 'CREATE_ALBUM_SUCCESS';
export const CREATE_ALBUM_FAILURE = 'CREATE_ALBUM_FAILURE';
export const CREATE_ALBUM_ERROR_CLEAR = 'CREATE_ALBUM_ERROR_CLEAR';

export const UPLOAD_IMAGE_TO_ALBUM_REQUEST = 'UPLOAD_IMAGE_TO_ALBUM_REQUEST';
export const UPLOAD_IMAGE_TO_ALBUM_SUCCESS = 'UPLOAD_IMAGE_TO_ALBUM_SUCCESS';
export const UPLOAD_IMAGE_TO_ALBUM_FAILURE = 'UPLOAD_IMAGE_TO_ALBUM_FAILURE';
export const UPLOAD_IMAGE_TO_ALBUM_ERROR_CLEAR =
  'UPLOAD_IMAGE_TO_ALBUM_ERROR_CLEAR';

export const DELETE_IMAGE_FROM_ALBUM_REQUEST =
  'DELETE_IMAGE_FROM_ALBUM_REQUEST';
export const DELETE_IMAGE_FROM_ALBUM_SUCCESS =
  'DELETE_IMAGE_FROM_ALBUM_SUCCESS';
export const DELETE_IMAGE_FROM_ALBUM_FAILURE =
  'DELETE_IMAGE_FROM_ALBUM_FAILURE';
export const DELETE_IMAGE_FROM_ALBUM_ERROR_CLEAR =
  'DELETE_IMAGE_FROM_ALBUM_ERROR_CLEAR';

export const RENAME_IMAGE_FROM_ALBUM_REQUEST =
  'RENAME_IMAGE_FROM_ALBUM_REQUEST';
export const RENAME_IMAGE_FROM_ALBUM_SUCCESS =
  'RENAME_IMAGE_FROM_ALBUM_SUCCESS';
export const RENAME_IMAGE_FROM_ALBUM_FAILURE =
  'RENAME_IMAGE_FROM_ALBUM_FAILURE';
export const RENAME_IMAGE_FROM_ALBUM_ERROR_CLEAR =
  'RENAME_IMAGE_FROM_ALBUM_ERROR_CLEAR';

export const DELETE_ALBUM_REQUEST = 'DELETE_ALBUM_REQUEST';
export const DELETE_ALBUM_SUCCESS = 'DELETE_ALBUM_SUCCESS';
export const DELETE_ALBUM_FAILURE = 'DELETE_ALBUM_FAILURE';
export const DELETE_ALBUM_ERROR_CLEAR = 'DELETE_ALBUM_ERROR_CLEAR';

export const EDIT_ALBUM_REQUEST = 'EDIT_ALBUM_REQUEST';
export const EDIT_ALBUM_SUCCESS = 'EDIT_ALBUM_SUCCESS';
export const EDIT_ALBUM_FAILURE = 'EDIT_ALBUM_FAILURE';
export const EDIT_ALBUM_ERROR_CLEAR = 'EDIT_ALBUM_ERROR_CLEAR';

export const ADD_ACCESS_TO_ALBUM_REQUEST = 'ADD_ACCESS_TO_ALBUM_REQUEST';
export const ADD_ACCESS_TO_ALBUM_SUCCESS = 'ADD_ACCESS_TO_ALBUM_SUCCESS';
export const ADD_ACCESS_TO_ALBUM_FAILURE = 'ADD_ACCESS_TO_ALBUM_FAILURE';
export const ADD_ACCESS_TO_ALBUM_ERROR_CLEAR =
  'ADD_ACCESS_TO_ALBUM_ERROR_CLEAR';

export const REMOVE_ACCESS_FROM_ALBUM_REQUEST =
  'REMOVE_ACCESS_FROM_ALBUM_REQUEST';
export const REMOVE_ACCESS_FROM_ALBUM_SUCCESS =
  'REMOVE_ACCESS_FROM_ALBUM_SUCCESS';
export const REMOVE_ACCESS_FROM_ALBUM_FAILURE =
  'REMOVE_ACCESS_FROM_ALBUM_FAILURE';
export const REMOVE_ACCESS_FROM_ALBUM_ERROR_CLEAR =
  'REMOVE_ACCESS_FROM_ALBUM_ERROR_CLEAR';

export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAILURE = 'CREATE_ORDER_FAILURE';
export const CREATE_ORDER_ERROR_CLEAR = 'CREATE_ORDER_ERROR_CLEAR';

export const GET_ORDER_REQUEST = 'GET_ORDER_REQUEST';
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS';
export const GET_ORDER_FAILURE = 'GET_ORDER_FAILURE';

export const UPDATE_ORDER_STATUS_REQUEST = 'UPDATE_ORDER_STATUS_REQUEST';
export const UPDATE_ORDER_STATUS_SUCCESS = 'UPDATE_ORDER_STATUS_SUCCESS';
export const UPDATE_ORDER_STATUS_FAILURE = 'UPDATE_ORDER_STATUS_FAILURE';
export const UPDATE_ORDER_STATUS_ERROR_CLEAR =
  'UPDATE_ORDER_STATUS_ERROR_CLEAR';

export const UPDATE_ORDER_COST_REQUEST = 'UPDATE_ORDER_COST_REQUEST';
export const UPDATE_ORDER_COST_SUCCESS = 'UPDATE_ORDER_COST_SUCCESS';
export const UPDATE_ORDER_COST_FAILURE = 'UPDATE_ORDER_COST_FAILURE';
export const UPDATE_ORDER_COST_ERROR_CLEAR = 'UPDATE_ORDER_COST_ERROR_CLEAR';

export const GET_NOTES_REQUEST = 'GET_NOTES_REQUEST';
export const GET_NOTES_SUCCESS = 'GET_NOTES_SUCCESS';
export const GET_NOTES_FAILURE = 'GET_NOTES_FAILURE';

export const CREATE_NOTE_REQUEST = 'CREATE_NOTE_REQUEST';
export const CREATE_NOTE_SUCCESS = 'CREATE_NOTE_SUCCESS';
export const CREATE_NOTE_FAILURE = 'CREATE_NOTE_FAILURE';
export const CREATE_NOTE_ERROR_CLEAR = 'CREATE_NOTE_ERROR_CLEAR';

export const EDIT_USER_REQUEST = 'EDIT_USER_REQUEST';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_FAILURE = 'EDIT_USER_FAILURE';
export const EDIT_USER_ERROR_CLEAR = 'EDIT_USER_ERROR_CLEAR';
